-   name: Install Composer
    become: yes
    shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer warn=no

-   name: Configure global composer.json
    become: yes
    become_user: "{{ user }}"
    template: src="composer.json.tpl" dest="/home/{{ user }}/.config/composer/composer.json"

-   name: Update global composer
    become: yes
    become_user: "{{ user }}"
    command: composer global update

#-   name: Install global composer repos
#    composer:
#        command: require
#        arguments: "{{ item }}"
#        working_dir: "/home/{{ user }}/.config/composer"
#    with_items: "{{ global_composer_packages }}"

-   name: Add composer to path
    lineinfile:
        dest: "~/.bash_profile"
        create: yes
        regexp: "export PATH=$PATH:/home/{{ user }}/.config/composer/vendor/bin"
        line: "export PATH=$PATH:/home/{{ user }}/.config/composer/vendor/bin"


-   name: Configure phpcs
    command: "/home/{{ user }}/.config/composer/vendor/bin/phpcs --config-set installed_paths /home/{{ user }}/.config/composer/vendor/escapestudios/symfony2-coding-standard"
    become: yes
    become_user: "{{ user }}"